on: [workflow_dispatch]
name: DeployAzureVM
jobs:
  CreateAzureVM:
    runs-on: windows-latest
    
    steps:
    # Checkout code from repo
    - name: checkout repo
      uses: actions/checkout@v1

    # Run powershell script to create VM
    - name: RunPowershellScriptFromRepo
      env: #Set secrets as environment variables
        creds : ${{ secrets.AZURE_CREDENTIALS }}
        AZURE_SUBSCRIPTION_NAME: ${{ secrets.AZURE_SUBSCRIPTION_NAME }}
      run: .\create-vm-azure.ps1
      shell: pwsh
